load("//:test_utils.bzl", "assert_output")

python_binary(
    name = "main",
    main = "main/main.py",
    deps = [
        # Add the dep to our py_lib library
        "root//buck2_lab/py_lib:printlib",
    ],
)

assert_output(
    name = "check_main",
    command = "$(exe_target :main)",
    output = "hello world from python toolchain",
)
